// Code generated by Kitex v0.0.3. DO NOT EDIT.
package echoservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/kitex-yyds/kitex-yyds/hello/kitex_gen/echo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler echo.EchoService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
