// Code generated by Kitex v0.0.3. DO NOT EDIT.

package hellothrift

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"github.com/kitex-yyds/kitex-yyds/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return helloThriftServiceInfo
}

var helloThriftServiceInfo = newServiceInfo()

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "HelloThrift"
	handlerType := (*api.HelloThrift)(nil)
	methods := map[string]kitex.MethodInfo{
		"echo": kitex.NewMethodInfo(echoHandler, newHelloThriftEchoArgs, newHelloThriftEchoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.0.3",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.HelloThriftEchoArgs)
	realResult := result.(*api.HelloThriftEchoResult)
	success, err := handler.(api.HelloThrift).Echo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloThriftEchoArgs() interface{} {
	return api.NewHelloThriftEchoArgs()
}

func newHelloThriftEchoResult() interface{} {
	return api.NewHelloThriftEchoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.HelloThriftEchoArgs
	_args.Req = req
	var _result api.HelloThriftEchoResult
	if err = p.c.Call(ctx, "echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
